### ISSUE TITLE
zipfile.BadZipFile: File is not a zip file on macOS  Mojave Version 10.14.6

### ISSUE THREAD

**Issue by hcrisgnya** [SAP/PyRFC#109]
Dear,
when installing /pyrfc-1.9.94-cp37-cp37m-macosx_10_14_x86_64.whl on my macbook with Python 3.7.4 and pip 19.1.1 from /usr/local/lib/python3.7/site-packages/pip (python 3.7), I get the following error. 
I also tried the same on an Ubuntu LTS, and I receive the same issue.

`pip3 install pyrfc-1.9.94-cp37-cp37m-macosx_10_14_x86_64.whl 
Processing ./pyrfc-1.9.94-cp37-cp37m-macosx_10_14_x86_64.whl
ERROR: Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/commands/install.py", line 352, in run
    resolver.resolve(requirement_set)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolve.py", line 131, in resolve
    self._resolve_one(requirement_set, req)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolve.py", line 294, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/resolve.py", line 242, in _get_abstract_dist_for
    self.require_hashes
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/operations/prepare.py", line 347, in prepare_linked_requirement
    progress_bar=self.progress_bar
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 873, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/download.py", line 807, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 628, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/local/lib/python3.7/site-packages/pip/_internal/utils/misc.py", line 505, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1225, in __init__
    self._RealGetContents()
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/zipfile.py", line 1292, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file`

**Comment by hlpupo** [comment]
I have the same issues, any solution

**Comment by bsrdjan** [comment]
The error usually happens when the wheel file is downloaded from the url pointing to GitHub wheel page (right click on wheel file in the `PyRFC/dist` folder):

https://github.com/SAP/PyRFC/blob/master/dist/pyrfc-1.9.97-cp37-cp37m-macosx_10_14_x86_64.whl

This is HTML content, not the wheel content. The wheel raw content should be downloaded from:

https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.97-cp37-cp37m-macosx_10_14_x86_64.whl

Please use the latest 1.9.97 version:

```shell
pip install https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.97-cp37-cp37m-macosx_10_14_x86_64.whl
```

**Comment by knguyen1794** [comment]
I had the same issue a couple of days ago.
@bsrdjan  is right. We have to point it to the right wheel content.

Alternatively, what we can do is to just download the file and put it in the same directory where your project is and 

`pip install pyrfc-1.9.97-cp37-cp37m-macosx_10_14_x86_64.whl`
