### ISSUE TITLE
Output of STFC_STRUCTURE fails to get converted to  json

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#126]
If I try to convert the output of `STFC_STRUCTURE` to json, then it fails:

```
Traceback (most recent call last):
    return output = json.dumps(output_data, ensure_ascii=False)
  File "/usr/lib64/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 210, in encode
    return ''.join(chunks)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf1 in position 1: ordinal not in range(128)
```

I use Python 2.7 and pyrfc 1.9.94.

You can reproduce this by modifing the example script: https://github.com/SAP/PyRFC/blob/master/examples/clientStfcStructure.py

**Comment by guettli** [comment]
I could cut it down into this issue:

```
d={u'RFCTABLE': [{u'RFCDATE': '', u'RFCFLOAT': 0.0, u'RFCDATA1': u'', u'RFCDATA2': u'', u'RFCTIME': u'000000', u'RFCCHAR1': u'', u'RFCINT4': 0, u'RFCHEX3': '\x00\x00\x00', u'RFCCHAR2': u'', u'RFCINT1': 0, u'RFCCHAR4': u'', u'RFCINT2': 0}, {u'RFCDATE': '', u'RFCFLOAT': 0.0, u'RFCDATA1': u'', u'RFCDATA2': u'', u'RFCTIME': u'000000', u'RFCCHAR1': u'', u'RFCINT4': 0, u'RFCHEX3': '\x00\x00\x00', u'RFCCHAR2': u'', u'RFCINT1': 0, u'RFCCHAR4': u'', u'RFCINT2': 0}, {u'RFCDATE': '', u'RFCFLOAT': 0.0, u'RFCDATA1': u'', u'RFCDATA2': u'', u'RFCTIME': u'000000', u'RFCCHAR1': u'', u'RFCINT4': 0, u'RFCHEX3': '\x00\x00\x00', u'RFCCHAR2': u'', u'RFCINT1': 0, u'RFCCHAR4': u'', u'RFCINT2': 0}, {u'RFCDATE': u'20191023', u'RFCFLOAT': 1.0, u'RFCDATA1': u'', u'RFCDATA2': u'', u'RFCTIME': u'124842', u'RFCCHAR1': u'X', u'RFCINT4': 1, u'RFCHEX3': '\xf1\xf2\xf3', u'RFCCHAR2': u'YZ', u'RFCINT1': 1, u'RFCCHAR4': u'TE1', u'RFCINT2': 1}], u'RESPTEXT': u'SAP R/3 Rel. 740   Sysid: TE1      Date: 20191023   Time: 124842', u'ECHOSTRUCT': {u'RFCDATE': '', u'RFCFLOAT': 0.0, u'RFCDATA1': u'', u'RFCDATA2': u'', u'RFCTIME': u'000000', u'RFCCHAR1': u'', u'RFCINT4': 0, u'RFCHEX3': '\x00\x00\x00', u'RFCCHAR2': u'', u'RFCINT1': 0, u'RFCCHAR4': u'', u'RFCINT2': 0}}
import json
json.dumps(d)
```

```
user@linux> python broken-json.py

Traceback (most recent call last):
  File "broken-json.py", line 3, in <module>
    json.dumps(d)
  File "/usr/lib64/python2.7/json/__init__.py", line 244, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xf1 in position 0: unexpected end of data
```

**Comment by guettli** [comment]
I found the offending data in above dict: `u'RFCHEX3': '\xf1\xf2\xf3',`.

If you remove this, then `json.dumps()` works.

**Comment by guettli** [comment]
In Python3 this code:
```

import json

json.dumps({u'RFCHEX3': b'\xf1\xf2\xf3'})
```

Results in this error message:

```
TypeError: Object of type 'bytes' is not JSON serializable
```

This is an issue that JSON can't handle binary data, not an issue of PyRFC.

But I hope this issue helps other developers to understand this.

**Comment by bsrdjan** [comment]
The standard Python JSON serialiser can't handle some of data types coming from ABAP to Python. Beside Python 3 bytes (binary strings in Python 2), Python date and time types can't be converted by standard json serialiser either. Default supported types are listed [here](https://docs.python.org/3/library/json.html#encoders-and-decoders).

Solution depends on project/application, like sending Base64 from ABAP, instead of binary strings and/or using date/time strings, instead of Python objects (PyRFC configuration). If non-supported type like bytes for example must be used in application, the standard Python json serialiser can be extended, like described [here](https://realpython.com/python-json/).

The Python 3 solution would be something like this:

```python

import base64
import json

def abap_encoder(obj):
    if isinstance(obj, bytes):
        return base64.b64encode(obj).decode()
    else:
        type_name = obj.__class__.__name__
        raise TypeError("Type is not JSON serializible:", type_name)

abap_data = {"RFCBYTES": bytes(b"\xf1\xf2\xf3")}

json_data = json.dumps(abap_data, default=abap_encoder)

print(json_data)
# {"RFCBYTES": "8fLz"}
```

Hope this helps.

**Comment by guettli** [comment]
@bsrdjan  thank you for this hint.

Maybe this should get added to the docs.

BTW, your code can be simplified to this:

```
import base64
import json

def abap_encoder(obj):
    if isinstance(obj, bytes):
        return base64.b64encode(obj).decode()
    type_name = obj.__class__.__name__
    raise TypeError("Type is not JSON serializible:", type_name)

abap_data = {"RFCBYTES": b"\xf1\xf2\xf3"}

json_data = json.dumps(abap_data, default=abap_encoder)

print(json_data)

```

**Comment by bsrdjan** [comment]
Let is leave it "documented" here, in this issue, for the time being. I would add to documentation if JSON interface added to PyRFC. Eventually in next release which would support Python 3 only and only critical fixes in Python 2.
