### ISSUE TITLE
pyrfc==1.9.99 --> RFC name must be bytes?

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#132]
After upgrading to pyrfc==1.9.99 I get this error:

```
Traceback (most recent call last):
  File "tmp/float-test.py", line 18, in <module>
    u'RFCHEX3': u'', u'RFCCHAR2': u'', u'RFCINT1': 0, u'RFCCHAR4': u'', u'RFCINT2': 0}, u'ECHOSTRUCT': {}})
  File "src/pyrfc/_pyrfc.pyx", line 390, in pyrfc._pyrfc.Connection.call
pyrfc._exception.RFCError: ('Remote function module name must be a string, received:', u'STFC_STRUCTURE')
```

Code:

```
from pyrfc import Connection

conn = Connection(...')


result = conn.call(u'STFC_STRUCTURE', **{u'RFCTABLE': [
        {u'RFCDATE': u'', u'RFCFLOAT': 1.23456, u'RFCDATA1': u'', u'RFCDATA2': u'', u'RFCTIME': u'', u'RFCCHAR1': u'', u'RFCINT4': 0, u'RFCH
        u'RFCINT1': 0, u'RFCCHAR4': u'', u'RFCINT2': 0},
        {u'RFCDATE': u'', u'RFCFLOAT': 0, u'RFCDATA1': u'', u'RFCDATA2': u'', u'RFCTIME': u'', u'RFCCHAR1': u'', u'RFCINT4': 0, u'RFCHEX3': 
        u'RFCINT1': 0, u'RFCCHAR4': u'', u'RFCINT2': 0},
        {u'RFCDATE': u'', u'RFCFLOAT': 0, u'RFCDATA1': u'', u'RFCDATA2': u'', u'RFCTIME': u'', u'RFCCHAR1': u'', u'RFCINT4': 0, u'RFCHEX3': 
        u'RFCINT1': 0, u'RFCCHAR4': u'', u'RFCINT2': 0}],
        u'IMPORTSTRUCT': {u'RFCDATE': u'', u'RFCFLOAT': 1.234, u'RFCDATA1': u'', u'RFCDATA2': u'', u'RFCTIME': u'', u'RFCCHAR1': u'', u'RFCI
        u'RFCHEX3': u'', u'RFCCHAR2': u'', u'RFCINT1': 0, u'RFCCHAR4': u'', u'RFCINT2': 0}, u'ECHOSTRUCT': {}})

print(result)
```

If I change `u'STFC_STRUCTURE'` to `'STFC_STRUCTURE'` it works (Python 2.7). 

Is this a bug or a feature?

**Comment by bsrdjan** [comment]
RFM name type check if string is added for Python 3, considering Python 3 strings are by default unicode (with or without "u" prefix).

That broke the backwards compatibility with Python 2, where unicode is accepted (no type check at all). Will be fixed for Python 2, to allow unicode.
