### ISSUE TITLE
use from pyrfc import *  there is an error

### ISSUE THREAD

**Issue by li2575250** [SAP/PyRFC#143]
The work environment python3.8
error info:

```
>>> from pyrfc import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python/lib/python3.8/site-packages/pyrfc/__init__.py", line 40, in <module>
    from pyrfc._pyrfc import (
ImportError: /usr/local/python/lib/python3.8/site-packages/pyrfc/_pyrfc.cpython-38-x86_64-linux-gnu.so: symbol RfcGetInt8, version libsapnwrfc.so not defined in file libsapnwrfc.so with link time reference
```

```
[root@localhost python]# ldconfig -p | grep sap
	libsapucum.so (libc6,x86-64) => /usr/local/sap/nwrfcsdk/lib/libsapucum.so
	libsapnwrfc.so (libc6,x86-64) => /usr/local/sap/nwrfcsdk/lib/libsapnwrfc.so
	libicuuc.so.34 (libc6,x86-64) => /usr/local/sap/nwrfcsdk/lib/libicuuc.so.34
	libicui18n.so.34 (libc6,x86-64) => /usr/local/sap/nwrfcsdk/lib/libicui18n.so.34
	libicudecnumber.so (libc6,x86-64) => /usr/local/sap/nwrfcsdk/lib/libicudecnumber.so
	libicudata.so.34 (libc6,x86-64) => /usr/local/sap/nwrfcsdk/lib/libicudata.so.34
	libgssapi_krb5.so.2 (libc6,x86-64) => /lib64/libgssapi_krb5.so.2
```
Ask everybody elder brother to help have a look. tks...

**Comment by bsrdjan** [comment]
Newer PyRFC releases require SAP NWRFC SDK 7.50 or later, with ABAP INT8 datatype support:

[SAP OSS Note 2573881 - SAP NetWeaver RFC SDK 7.50 -- Initial delivery](https://launchpad.support.sap.com/#/notes/2573881)

SAP NWRFC SDK upgrade should fix.

**Comment by li2575250** [comment]
I've lowered the version, and then it's done.tks...
