### ISSUE TITLE
Could not convert from 8400 codepage to 4103 codepage

### ISSUE THREAD

**Issue by kkeitam** [SAP/PyRFC#16]
test:

> > > rel = conn.call('ZRFC_SD_903', OPTION='A')

Traceback (most recent call last):
  File "<pyshell#17>", line 1, in <module>
    rel = conn.call('ZRFC_SD_903', OPTION='A')
  File "pyrfc_pyrfc.pyx", line 363, in pyrfc._pyrfc.Connection.call (pyrfc_pyrfc.c:3955)
  File "pyrfc_pyrfc.pyx", line 218, in pyrfc._pyrfc.Connection._error (pyrfc_pyrfc.c:3044)
ExternalRuntimeError: RFC_CONVERSION_FAILURE (rc=22): key=RFC_CONVERSION_FAILURE, message=Could not convert from 8400 codepage to 4103 codepage, rc = 512 [MSG: class=, type=, number=, v1-4:=;;;]

**Comment by bsrdjan** [comment]
Did you check systems/communication settings per [SAP OSS Note 1021459](http://service.sap.com/sap/support/notes/1021459) and related notes ?

**Comment by bsrdjan** [comment]
Closed due to inactivity
