### ISSUE TITLE
How to build Cloud Foundry Python app (including SAP NW RFC SDK)?

### ISSUE THREAD

**Issue by ankur0101** [SAP/PyRFC#205]
Hello,

I am using Ubuntu based environment to run PyRFC. I took following steps:

- Downloaded nwrfcsdk from sap marketplace for Linux On 64-bit and saved in in /root as /root/nwrfcsdk
- Ran command `export SAPNWRFC_HOME=/root/nwrfcsdk`
- Ran command `pip3 install cython`
- Ran command `pip3 install pynwrfc`
- Ran command `python3`
- Ran `from pyrfc import Connection`

This immediately gave following error message:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/pyrfc/__init__.py", line 29, in <module>
    from .pyrfc import (
ImportError: libsapnwrfc.so: cannot open shared object file: No such file or directory
```
If I look inside __init__.py, I see it is trying to load SO (shared object) file as module using 
`os.add_dll_directory(os.path.join(os.environ["SAPNWRFC_HOME"], "lib"))`
Which can be found here 
[https://github.com/SAP/PyRFC/blob/master/src/pyrfc/__init__.py](https://github.com/SAP/PyRFC/blob/master/src/pyrfc/__init__.py)
I am not sure this is the correct approach to load Shared object files in linux since method add_dll_directory is being called after checking OS type as **nt**, I could not see any check mechanism to detect unix OS type.

Also please find the screenshot below for the structure of /root/nwrfcsdk

![image](https://user-images.githubusercontent.com/2085372/96831074-06492080-145a-11eb-8311-aa7540e1ae40.png)

What exactly needs to be done here to get this thing working?
Thanks

EDIT: I see no code for unix os types is written in this library.

![image](https://user-images.githubusercontent.com/2085372/96832133-e6b2f780-145b-11eb-8633-0eb5aa3e4711.png)

I will try to push unix adaptation but I think it would be better that someone managing this repo can take care of it.

**Comment by ankur0101** [comment]
The temporary workaround is to install shared object files via ldconfig. I took following steps and now error has disappeared.

- Moved nwrfcsdk from /root/nwrfcsdk to /usr/local/sap/nwrfcsdk
- Created nwrfcsdk.conf file in /etc/ld.so.conf.d/ and added content as /usr/local/sap/nwrfcsdk/lib
- Ran command ldconfig
- Ran command ldconfig -p | grep sap which showed loaded library 

![image](https://user-images.githubusercontent.com/2085372/96838818-f9cac500-1465-11eb-938e-07f3d8ab7415.png)

I think this could get addressed into library since currently I am trying to use pyrfc in SAP Cloud foundry where root access to container could not be gained and unsure how to create `nwrfcsdk.conf` in `/etc/ld.so.conf.d/` and run command `ldconfig` via `cf push`.

Credits: [https://medium.com/codingtown/install-sap-nw-rfc-sdk-in-ubuntu-18-04-3-lts-50e42b4dfe66](https://medium.com/codingtown/install-sap-nw-rfc-sdk-in-ubuntu-18-04-3-lts-50e42b4dfe66)

**Comment by bsrdjan** [comment]
If you look only 4 lines above the `os.add_dll_directory()` statement in `init.py`, there is a [comment]( https://docs.python.org/3.8/whatsnew/3.8.html#bpo-36085-whatsnew) why this statement is added and relevant for Windows only.

Your main questions I think are how to deploy SAP NWRFC SDK to Cloud Foundry and how to use the PyRFC from Cloud Foundry. 

Technically, SAP NWRFC SDK can be deployed using CF [Pre-Runtime Hooks](https://docs.cloudfoundry.org/devguide/deploy-apps/deploy-app.html#profile) and PyRFC can be also deployed the standard way. The challenge is RFC channel from SAP Cloud Platform to ABAP backend, currently supported only for Java runtimes in Neo and the SAP Java Buildpack in Cloud Foundry.

For Python (and/or NodeJS) you can create the feature request for SAP Secure Cloud Connector, to enable SAP NWRFC SDK usage within SAP Cloud Platform Connectivity context and be able to use the Cloud Connector also from Python. 

Please see the same question for NodeJS: https://github.com/SAP/node-rfc/issues/79

**Comment by ankur0101** [comment]
Thanks @bsrdjan for changing title 👍 

To run ldconfig via cf push using .profile, it requires root level permissions since it returns Permission Denied error.
I am not experienced in cloud foundry but as per my observation, I see CF installs dependencies from requirements.txt first and then triggers .profile Hence this results error saying "Environment variable SAPNWRFC_HOME not defined" even though it has been mentioned in manifest.yml as 

```
env:
    SAPNWRFC_HOME: /home/vcap/app/nwrfcsdk
```
Is there any way to get Shared object files uploaded before running requirments.txt?

**Comment by bsrdjan** [comment]
Sorry that I can't help further with PyRFC and NWRFC SDK packaging on Cloud Foundry, without SAP NWRFC SDK being supported on Cloud Foundry. Would you mind to create a feature request for that on influence.sap.com ?

**Comment by ankur0101** [comment]
I was able to push pyrfc with NWRFC's shared object into sap cloud foundry via docker image. Thanks for your assistance @bsrdjan

**Comment by bsrdjan** [comment]
The feature request to enable SAP NWRFC SDK usage on Cloud Foundry, in Connectivity context, can be created for:

`Security Services` category of the [SAP Cloud Platform – Platform Foundation](https://influence.sap.com/sap/ino/#/campaign/2277)

**Comment by bsrdjan** [comment]
Here the feature request for node-rfc cloud connectivity. You may comment or vote for,  or create similar request for PyRFC

You may vote for the new request, linked here: https://github.com/SAP/node-rfc/issues/145#issuecomment-781209573

**Comment by bsrdjan** [comment]
Here the current status and how to build Cloud Foundry Node.JS app with SAP NW RFC SDK:

[ABAP RFC connectivity from Kyma and BTP Node.JS buildpack](https://blogs.sap.com/2023/10/26/abap-rfc-connectivity-from-btp-node.js-buildpack/)

 It works the sam way with Python. If any questions just share them here
