### ISSUE TITLE
ImportError: DLL load failed while importing pyrfc

### ISSUE THREAD

**Issue by jduncan8142** [SAP/PyRFC#206]
Have seen a few issues open on similar problems but so far nothing has resolved the issue. When attempting to import pyrfc I'm getting the below error. 

Error:
`(venv) PS E:\puresap\backend> uvicorn main:app --reload
INFO:     Uvicorn running on http://127.0.0.1:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [2744] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "E:\Program Files\Python38\lib\multiprocessing\process.py", line 315, in _bootstrap
    self.run()
  File "E:\Program Files\Python38\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "e:\puresap\venv\lib\site-packages\uvicorn\subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "e:\puresap\venv\lib\site-packages\uvicorn\main.py", line 419, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "E:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "e:\puresap\venv\lib\site-packages\uvicorn\main.py", line 426, in serve
    config.load()
  File "e:\puresap\venv\lib\site-packages\uvicorn\config.py", line 328, in load
    self.loaded_app = import_from_string(self.app)
  File "e:\puresap\venv\lib\site-packages\uvicorn\importer.py", line 23, in import_from_string
    raise exc from None
  File "e:\puresap\venv\lib\site-packages\uvicorn\importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "E:\Program Files\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File ".\main.py", line 7, in <module>
    from pure_sap.deleted_hu_check import DeletedHuCheck
  File ".\..\pure_sap\deleted_hu_check.py", line 18, in <module>
    from pure_sap.read_table import ReadTable
  File ".\..\pure_sap\read_table.py", line 3, in <module>
    from pure_sap.rfc_connection import RfcConnection
  File ".\..\pure_sap\rfc_connection.py", line 1, in <module>
    import pyrfc
  File "e:\puresap\venv\lib\site-packages\pyrfc\__init__.py", line 29, in <module>
    from .pyrfc import (
ImportError: DLL load failed while importing pyrfc: The specified procedure could not be found.`

Python version
`(venv) PS E:\puresap\backend> python --version
Python 3.8.6`

Visual C++ Redistributable Package for Visual Studio 2013 is installed as per the guide [here](https://github.com/SAP/PyRFC/blob/master/README.md#windows).

pyrfc was installed in venv with `pip install pynwrfc`

Running for PS as you can see in the output with the error msg on Windows Server 2016. 

`(venv) PS E:\puresap\backend> echo $env:SAPNWRFC_HOME
C:\nwrfcsdk`

`(venv) PS E:\puresap\backend> dir $env:SAPNWRFC_HOME\lib

    Directory: C:\nwrfcsdk\lib

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
d-----        11/8/2020  12:13 AM                include
-a----       11/25/2019   4:36 PM        8837632 icudt34.dll
-a----       11/25/2019   3:51 PM        1097216 icuin34.dll
-a----       11/25/2019   4:35 PM        1174528 icuuc34.dll
-a----       11/25/2019   4:36 PM          68096 libicudecnumber.dll
-a----       11/25/2019   4:36 PM         197120 libsapucum.dll
-a----       11/25/2019   4:36 PM          24392 libsapucum.lib
-a----       11/25/2019   4:36 PM         282394 sapdecfICUlib.lib
-a----       11/25/2019   4:31 PM        5121024 sapnwrfc.dll
-a----       11/25/2019   4:30 PM          45854 sapnwrfc.lib

`

I do notice there is an issue in:
`(venv) PS E:\puresap\backend> findstr Patch sapnwrfc.dll
FINDSTR: Cannot open sapnwrfc.dll`

Not sure what to check next. I've reviewed auth for the files and access seems to be fine but not sure what sapnwrfc.dll cannot be opened.

**Comment by bsrdjan** [comment]
The SAP NWRFC SDK looks like an older release and the loading fails because newer SDK API is missing.

Please try with the current SDK release.

**Comment by jduncan8142** [comment]
Updating the SDK worked. Thanks
