### ISSUE TITLE
Example clientPrintDescription doesnt work

### ISSUE THREAD

**Issue by muellma-items** [SAP/PyRFC#214]
Hi,
when running the example file clientPrintDescription.py I get an error in the following line:

`        func_desc = connection.get_function_description(function_name)`

```
Traceback (most recent call last):
  File "C:\XXXXX\pyRFC\clientPrintDescription.py", line 106, in <module>
    main(sys.argv[1])
  File "C:\XXXXX\python\pyRFC\clientPrintDescription.py", line 31, in main
    func_desc = connection.get_function_description(function_name)
  File "src/pyrfc/_pyrfc.pyx", line 406, in pyrfc.pyrfc.Connection.get_function_description
  File "src/pyrfc/_pyrfc.pyx", line 2022, in pyrfc.pyrfc.wrapFunctionDescription
  File "src/pyrfc/_pyrfc.pyx", line 1150, in pyrfc.pyrfc.FunctionDescription.add_parameter
NameError: name '_direction2rfc' is not defined
```

I have seen in another issue that there might be a problem with the nwrfcsdk in PL7? Is this related? It's the only version I have available for testing at the moment.

**Comment by bsrdjan** [comment]
The `clientPrintDescription.py` is deprecated and will be removed. If you are interested in RFM parameters' names and data types, there is a [rfmcall](https://github.com/sap/fundamental-tools#rfmcall-and-backendpy) utility of [sap/fundamental-tools](https://github.com/sap/fundamental-tools). Would it be a viable alternative in your case?

**Comment by muellma-items** [comment]
Thanks for the quick reply & alternative. For now I'll just stick to SE37 though. I was mostly worried I had some issue with my installation.
