### ISSUE TITLE
RFC_ABAP_RUNTIME_FAILURE (rc=3): key=ASSIGN_CASTING_ILLEGAL_CAST, message=Error with ASSIGN ... CASTING in program SAPLSDTX

### ISSUE THREAD

**Issue by smartexpert** [SAP/PyRFC#232]
**Describe the bug**
After successful connection, the following call throws an error:

```
result = conn.call("RFC_READ_TABLE", QUERY_TABLE='REPOSRC', DELIMITER='|', FIELDS = ['PROGNAME'], OPTIONS=[{'TEXT':"PROGNAME = 'ZZ_TEST'"}], ROWCOUNT = 1000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "src/pyrfc/_pyrfc.pyx", line 500, in pyrfc.pyrfc.Connection.call
  File "src/pyrfc/_pyrfc.pyx", line 332, in pyrfc.pyrfc.Connection._error
pyrfc._exception.ABAPRuntimeError: RFC_ABAP_RUNTIME_FAILURE (rc=3): key=ASSIGN_CASTING_ILLEGAL_CAST, message=Error with ASSIGN ... CASTING in program SAPLSDTX                                . [MSG: class=, type=, number=, v1-4:=;;;]
```
**To Reproduce**
```
from pyrfc import Connection
conn = Connection(ashost='XXX', sysnr='00', client='100', user='XXX', passwd='XXX')
result = conn.call("RFC_READ_TABLE", QUERY_TABLE='REPOSRC', DELIMITER='|', FIELDS = ['PROGNAME'], OPTIONS=[{'TEXT':"PROGNAME = 'ZBC_ACTT_EXTRACT'"}], ROWCOUNT = 1000)
```

I have tested this by calling several other tables and noticed that the issue only occurs if the table has a field with data type rawstring (RSTR) / xstring.

**Environment**
 - OS:  x86_64 GNU/Linux
 - Running in docker? Yes, but get the same result outside of docker
 - PyRFC version = 2.4.1 using NWRFC SDK 7.5 PL 8

**Comment by bsrdjan** [comment]
The issue is not related to `PyRFC` but to `RFC_READ_TABLE` limitations. Calling `RFC_READ_TABLE` from ABAP transaction, using these same parameters, should raise the same exception. Please try that and check:

- SAP Note [382318 - FAQ|Function module RFC_READ_TABLE](https://launchpad.support.sap.com/#/notes/382318)
- [SCN: RFC_READ_TABLE with filter GUID](https://answers.sap.com/questions/12356363/rfcreadtable-with-filter-guid.html).

**Comment by qsecofr** [comment]
Hello,

i am running into a similar error, but with /SAPDS/RFC_READ_TABLE2. I've select only a small number of fileds (no RSTR field among them).

Execution with SE37 works fine.
