### ISSUE TITLE
No module named 'ConfigParser'

### ISSUE THREAD

**Issue by Tset-Noitamotua** [SAP/PyRFC#25]
I tried to run `clientStfcStructure.py` (**with Python 3.5.2 - 64bit**) which resulted in:

```
Traceback (most recent call last):
  File "clientStfcStructure.py", line 5, in <module>
    from ConfigParser import ConfigParser
ImportError: No module named 'ConfigParser'
```

Then I install "ConfigParser" with `pip install ConfigParser`  which gave me `configparser (3.5.0)`. Then I tried to run `clientStfcStructure.py` again getting the same error as above.

After renaming `from ConfigParser` to `from configparser` in [line 5 of clientStfcStructure.py](https://github.com/SAP/PyRFC/blob/master/examples/clientStfcStructure.py#L5) I get next error:

```
Traceback (most recent call last):
  File "clientStfcStructure.py", line 35, in <module>
    main()
  File "clientStfcStructure.py", line 31, in main
    result = conn.call('STFC_STRUCTURE', IMPORTSTRUCT=imp)
  File "pyrfc\_pyrfc.pyx", line 359, in pyrfc._pyrfc.Connection.call (pyrfc\_pyrfc.c:4065)
  File "pyrfc\_pyrfc.pyx", line 1531, in pyrfc._pyrfc.fillFunctionParameter (pyrfc\_pyrfc.c:17862)
  File "pyrfc\_pyrfc.pyx", line 1632, in pyrfc._pyrfc.fillVariable (pyrfc\_pyrfc.c:19179)
  File "pyrfc\_pyrfc.pyx", line 1568, in pyrfc._pyrfc.fillVariable (pyrfc\_pyrfc.c:18346)
  File "pyrfc\_pyrfc.pyx", line 1543, in pyrfc._pyrfc.fillStructureField (pyrfc\_pyrfc.c:17977)
  File "pyrfc\_pyrfc.pyx", line 1632, in pyrfc._pyrfc.fillVariable (pyrfc\_pyrfc.c:19179)
  File "pyrfc\_pyrfc.pyx", line 1579, in pyrfc._pyrfc.fillVariable (pyrfc\_pyrfc.c:18493)
  File "pyrfc\_pyrfc.pyx", line 1639, in pyrfc._pyrfc.fillBytes (pyrfc\_pyrfc.c:19306)
TypeError: ('expected bytes, str found', 'RFCHEX3', 'IMPORTSTRUCT')
```

**Comment by Tset-Noitamotua** [comment]
The second error mentioned above is related to Python 3 uncompatibility of the code.

Running with Python 2.7.12 (64bit) the result is as expected:

```
[PYTHON_2764] λ python clientStfcStructure.py
{u'ECHOSTRUCT': {u'RFCCHAR1': u'a',
                 u'RFCCHAR2': u'ij',
                 u'RFCCHAR4': u'bcde',
                 u'RFCDATA1': u'kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk',
                 u'RFCDATA2': u'llllllllllllllllllllllllllllllllllllllllllllllllll',
                 ...

```

**Comment by I057542** [comment]
I encountered the same issue, and I changed the code:

`from ConfigParser import ConfigParser
to 
from configparser import ConfigParser`

and it works on python 3.6

**Comment by bsrdjan** [comment]
Thanks @Tset-Noitamotua and @I057542, is fixed.
