### ISSUE TITLE
[Python3.5] iteritems() --> items()

### ISSUE THREAD

**Issue by Tset-Noitamotua** [SAP/PyRFC#36]
I have this code:

```python
def call_bapi(self, bapi, **kwargs):
        try:
            result = self.sap.call(bapi, **kwargs)
            return result
        except:
            raise
```

failing with

```shell
AttributeError: iteritems	
09:26:49.587	DEBUG	Traceback (most recent call last):
  File "c:\users\ME\envs\rf_3564\lib\site-packages\sap_library-0.0.1-py3.5.egg\SAP\SAP.py", line 77, in call_bapi
    result = self.sap.call(bapi, **kwargs)
  File "src/pyrfc/_pyrfc.pyx", line 373, in pyrfc._pyrfc.Connection.call (src/pyrfc\_pyrfc.c:4442)
  File "src/pyrfc/_pyrfc.pyx", line 1543, in pyrfc._pyrfc.fillFunctionParameter (src/pyrfc\_pyrfc.c:18589)
  File "src/pyrfc/_pyrfc.pyx", line 1579, in pyrfc._pyrfc.fillVariable (src/pyrfc\_pyrfc.c:19043)
  File "c:\users\ME\envs\rf_3564\lib\site-packages\robot\utils\dotdict.py", line 28, in __getattr__
    raise AttributeError(key)
```

A quick google search brought me [here](https://github.com/fabianvf/python-rake/pull/6/files) which seems to be a similar case?

**Comment by Tset-Noitamotua** [comment]
I think `dict.iteritems()` is not compatible with Python 3 any more as it was removed.

![image](https://cloud.githubusercontent.com/assets/5635462/22694685/65173008-ed48-11e6-9a20-920603e2a51d.png)

see [Python Wiki](https://wiki.python.org/moin/Python3.0/#Built-In_Changes)
or [Stackoverflow](http://stackoverflow.com/a/30418498/4445175)

**Comment by bsrdjan** [comment]
Thanks, now in 1.9.7 master.
