### ISSUE TITLE
Undefined symbol: PyFPE_jbuf with Python 3.5+

### ISSUE THREAD

**Issue by pnpavlov** [SAP/PyRFC#61]
Hello,

I'm trying to migrate a PyRFC build from a virtual mcahine running Python 3.4 to a docker container, hoping to use pyhton 3.6. I spend half day so far trying to find out the root cause with no luck. I hope you can guide me. 
When I pull the docker python:3.4 image based on deb8 and I easy_install-3.4 PyRFC-1.9.8/dist/pyrfc-1.9.4-py3.4-linux-x86_64.egg everything is fine and I can python -c "from pyrfc import Connection".

When I pul lthe docker python:3.6 image based on deb8 and I easy_install-3.6 PyRFC-1.9.8/dist/pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl (or pip3 install) I get ImportError: /usr/local/lib/python3.6/site-packages/pyrfc-1.9.8-py3.6-linux-x86_64.egg/pyrfc/_pyrfc.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

Could you please help me out to run the pyrfc properly on python3.6 ? Could it be that nwrfc750P_0-70002752 is not the right NW binary for 3.6 and is only 3.4 compatible? Thank you!

Regards,
Pavel

Full details:
- Working installation for Python 3.4
```
======= 3.4 =======
# docker run -ti --rm --name dlc python:3.4 bash

root@cb730918d719:/# cat /etc/os-release
	PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
	NAME="Debian GNU/Linux"
	VERSION_ID="8"
	VERSION="8 (jessie)"
	ID=debian
	HOME_URL="http://www.debian.org/"
	SUPPORT_URL="http://www.debian.org/support"
	BUG_REPORT_URL="https://bugs.debian.org/"
root@cb730918d719:/# python -V
	Python 3.4.8
root@cb730918d719:/# ldd --version
	ldd (Debian GLIBC 2.19-18+deb8u10) 2.19

root@be6e81621b69:/# apt-get update; apt-get install -y unzip

# docker cp PyRFC-1.9.8.zip dlc:/dlc/; docker cp nwrfc750P_0-70002752-linux.zip dlc:/dlc/

root@cb730918d719:/# cd /dlc
root@cb730918d719:/dlc# unzip nwrfc750P_0-70002752-linux.zip -d /usr/sap/
root@cb730918d719:/dlc# cat <<EOF >> /etc/ld.so.conf.d/nwrfcsdk.conf
> # include nwrfcsdk
> /usr/sap/nwrfcsdk/lib
> EOF
root@cb730918d719:/dlc# ldconfig
root@cb730918d719:/dlc# unzip PyRFC-1.9.8.zip
root@cb730918d719:/dlc# easy_install-3.4 PyRFC-1.9.8/dist/pyrfc-1.9.4-py3.4-linux-x86_64.egg
	Processing pyrfc-1.9.4-py3.4-linux-x86_64.egg
	creating /usr/local/lib/python3.4/site-packages/pyrfc-1.9.4-py3.4-linux-x86_64.egg
	Extracting pyrfc-1.9.4-py3.4-linux-x86_64.egg to /usr/local/lib/python3.4/site-packages
	Adding pyrfc 1.9.4 to easy-install.pth file

	Installed /usr/local/lib/python3.4/site-packages/pyrfc-1.9.4-py3.4-linux-x86_64.egg
	Processing dependencies for pyrfc==1.9.4
	Finished processing dependencies for pyrfc==1.9.4
	
root@cb730918d719:/dlc# python -c "from pyrfc import Connection"
root@cb730918d719:/dlc#
```

- Failing installations for Python  3.5 & 3.6
```
======= 3.5 =======
# docker run -ti --rm --name dlc python:3.5 bash

root@be6e81621b69:/# mkdir /dlc
root@be6e81621b69:/# cat /etc/os-release
	PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
	NAME="Debian GNU/Linux"
	VERSION_ID="8"
	VERSION="8 (jessie)"
	ID=debian
	HOME_URL="http://www.debian.org/"
	SUPPORT_URL="http://www.debian.org/support"
	BUG_REPORT_URL="https://bugs.debian.org/"
root@be6e81621b69:/# python -V
	Python 3.5.5
	
root@be6e81621b69:/# ldd --version
	ldd (Debian GLIBC 2.19-18+deb8u10) 2.19
	Copyright (C) 2014 Free Software Foundation, Inc.
	This is free software; see the source for copying conditions.  There is NO
	warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

root@be6e81621b69:/# apt-get update; apt-get install -y unzip

# docker cp PyRFC-1.9.8.zip dlc:/dlc/; docker cp nwrfc750P_0-70002752-linux.zip dlc:/dlc/

root@be6e81621b69:/# cd /dlc
root@be6e81621b69:/dlc# unzip nwrfc750P_0-70002752-linux.zip -d /usr/sap/
root@be6e81621b69:/dlc# cat <<EOF >> /etc/ld.so.conf.d/nwrfcsdk.conf
# include nwrfcsdk
/usr/sap/nwrfcsdk/lib
EOF
root@be6e81621b69:/dlc# ldconfig
root@be6e81621b69:/dlc# unzip PyRFC-1.9.8.zip
root@be6e81621b69:/dlc# easy_install-3.5 PyRFC-1.9.8/dist/pyrfc-1.9.5-py3.5-linux-x86_64.egg
root@be6e81621b69:/dlc# python -c "from pyrfc import Connection"
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/usr/local/lib/python3.5/site-packages/pyrfc-1.9.5-py3.5-linux-x86_64.egg/pyrfc/__init__.py", line 22, in <module>
		from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription, FunctionDescription, Server
	ImportError: /usr/local/lib/python3.5/site-packages/pyrfc-1.9.5-py3.5-linux-x86_64.egg/pyrfc/_pyrfc.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

root@be6e81621b69:/dlc# pip3 uninstall pyrfc
	Uninstalling pyrfc-1.9.5:
	  /usr/local/lib/python3.5/site-packages/pyrfc-1.9.5-py3.5-linux-x86_64.egg
	Proceed (y/n)? y
	Successfully uninstalled pyrfc-1.9.5
root@be6e81621b69:/dlc# pip3 install PyRFC-1.9.8/dist/pyrfc-1.9.5-cp35-cp35m-linux_x86_64.whl
	Processing ./PyRFC-1.9.8/dist/pyrfc-1.9.5-cp35-cp35m-linux_x86_64.whl
	Requirement already satisfied: setuptools in /usr/local/lib/python3.5/site-packages (from pyrfc==1.9.5)
	Installing collected packages: pyrfc
	Successfully installed pyrfc-1.9.5
root@be6e81621b69:/dlc# python -c "from pyrfc import Connection"
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/usr/local/lib/python3.5/site-packages/pyrfc/__init__.py", line 22, in <module>
		from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription, FunctionDescription, Server
	ImportError: /usr/local/lib/python3.5/site-packages/pyrfc/_pyrfc.cpython-35m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf

======= 3.6 =======
wdflbmd22191:~ # docker run -ti --rm --name dlc python:3.6 bash

root@6b7ecd3b69c3:/# mkdir /dlc
root@6b7ecd3b69c3:/# cat /etc/os-release
	PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
	NAME="Debian GNU/Linux"
	VERSION_ID="8"
	VERSION="8 (jessie)"
	ID=debian
	HOME_URL="http://www.debian.org/"
	SUPPORT_URL="http://www.debian.org/support"
	BUG_REPORT_URL="https://bugs.debian.org/"

root@6b7ecd3b69c3:/# python -V
	Python 3.6.4
root@6b7ecd3b69c3:/# ldd --version
	ldd (Debian GLIBC 2.19-18+deb8u10) 2.19

root@6b7ecd3b69c3:/# apt-get update; apt-get install -y unzip

# docker cp PyRFC-1.9.8.zip dlc:/dlc/; docker cp nwrfc750P_0-70002752-linux.zip dlc:/dlc/

root@6b7ecd3b69c3:/dlc# unzip nwrfc750P_0-70002752-linux.zip -d /usr/sap/

root@6b7ecd3b69c3:/dlc# cat <<EOF >> /etc/ld.so.conf.d/nwrfcsdk.conf
# include nwrfcsdk
/usr/sap/nwrfcsdk/lib
EOF
root@6b7ecd3b69c3:/dlc# ldconfig

root@6b7ecd3b69c3:/dlc# easy_install-3.6 PyRFC-1.9.8/dist/pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl
	Processing pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl
	Installing pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl to /usr/local/lib/python3.6/site-packages
	writing requirements to /usr/local/lib/python3.6/site-packages/pyrfc-1.9.8-py3.6-linux-x86_64.egg/EGG-INFO/requires.txt
	Adding pyrfc 1.9.8 to easy-install.pth file

	Installed /usr/local/lib/python3.6/site-packages/pyrfc-1.9.8-py3.6-linux-x86_64.egg
	Processing dependencies for pyrfc==1.9.8
	Finished processing dependencies for pyrfc==1.9.8
root@6b7ecd3b69c3:/dlc# python -c "from pyrfc import Connection"
	Traceback (most recent call last):
	  File "<string>", line 1, in <module>
	  File "/usr/local/lib/python3.6/site-packages/pyrfc-1.9.8-py3.6-linux-x86_64.egg/pyrfc/__init__.py", line 22, in <module>
		from pyrfc._pyrfc import get_nwrfclib_version, Connection, TypeDescription, FunctionDescription, Server
	ImportError: /usr/local/lib/python3.6/site-packages/pyrfc-1.9.8-py3.6-linux-x86_64.egg/pyrfc/_pyrfc.cpython-36m-x86_64-linux-gnu.so: undefined symbol: PyFPE_jbuf
```

**Comment by bsrdjan** [comment]
Hi Pavel,
published pyrfc wheels are built with SAP NW RFC SDK version 7.4 and not guaranteed to work with version 7.5, regardless which Python version.
SAP NW RFC SDK is backwards compatible and the latest version is always recommended.
When in doubt about published wheels, you can always built your own from source. Just clone the PyRFC on docker image, cd to PyRFC and run:
```shell
python setup.py bdist_wheel
```
That should produce the wheel for Python and SAP NW RFC SDK installed on docker Linux. Here is the one I am using with Python 3.6.3 and SAP NW RFC SDK 7.5, built on Ubuntu 17.10. It may be good for docker Linux as well built from source is always best.

[pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl.zip](https://github.com/SAP/PyRFC/files/1825384/pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl.zip)

Hope this helps.

Kind regards,
Srdjan

**Comment by pnpavlov** [comment]
Hi @bsrdjan ,

Thank you! It would have taken me some time to figure that out without your support! 
I've tried out compiling the PyRFC 1.9.8 against the nwrfc lib 7.50 with python 3.6.4 and seems to work (at least no import time error).
I'm closing the issue - please drop me an message in skype or email if you would like me to open pull request with an .md document for this procedure ;-)

```
# nwrfc
unzip nwrfc750P_0-70002752-linux.zip -d /usr/sap/
mv /usr/sap/META-INF /usr/sap/nwrfcsdk
mv /usr/sap/nwrfc750P_0.manifest /usr/sap/nwrfcsdk
cat <<EOF >> /etc/ld.so.conf.d/nwrfcsdk.conf
# include nwrfcsdk
/usr/sap/nwrfcsdk/lib
EOF
cat /etc/ld.so.conf.d/nwrfcsdk.conf
ldconfig

# pyrfc
unzip zxvf PyRFC-1.9.8.zip
pip3 install Cython
export SAPNWRFC_HOME=/usr/sap/nwrfcsdk/
export PYTHONSOURCE=/tmp/Python-3.6.4/
python3 setup.py bdist_wheel
sed -i "s/0.27.3/0.28.1/g' setup.py
python3 setup.py install
python3 -c "from pyrfc import Connection"
```

Regards,
Pavel
