### ISSUE TITLE
I cant install it with PIP

### ISSUE THREAD

**Issue by juan-vargas** [SAP/PyRFC#62]
Dear Sirs,

When I try to install it i get the following error:

 pip install --upgrade https://github.com/SAP/PyRFC/blob/master/dist/pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl
Collecting pyrfc==1.9.8 from https://github.com/SAP/PyRFC/blob/master/dist/pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl
  Downloading https://github.com/SAP/PyRFC/blob/master/dist/pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl
     / 40kB 483kB/s
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python3.6/site-packages/pip/commands/install.py", line 335, in run
    wb.build(autobuilding=True)
  File "/usr/local/lib/python3.6/site-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python3.6/site-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 821, in unpack_url
    hashes=hashes
  File "/usr/local/lib/python3.6/site-packages/pip/download.py", line 663, in unpack_http_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/local/lib/python3.6/site-packages/pip/utils/__init__.py", line 599, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/local/lib/python3.6/site-packages/pip/utils/__init__.py", line 484, in unzip_file
    zip = zipfile.ZipFile(zipfp, allowZip64=True)
  File "/usr/local/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/usr/local/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

Any idea what could be the problem?

Kind regards,

Juan

**Comment by juan-vargas** [comment]
I found the solution. Thanks!

**Comment by aregmax** [comment]
Could you share your solution?
Thx

**Comment by juan-vargas** [comment]
Hello, 

I am not sure, because it was some months ago, but I think that I was using the file downloaded from Github, but not the good one, you should download raw file.

This one: https://github.com/SAP/PyRFC/raw/master/dist/pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl instead of this one: https://github.com/SAP/PyRFC/blob/master/dist/pyrfc-1.9.8-cp36-cp36m-linux_x86_64.whl

I hope this helps!

Kind regards,

Juan

**Comment by bsrdjan** [comment]
The package is not available on pip, only github.

**Comment by aregmax** [comment]
Thx guys.
I repeated steps again. It works.
I was getting the same error (like in the first post) when I run pip with https address.
Now I downloaded it and run pip with local file and its ok.
Thx

**Comment by juan-vargas** [comment]
You are welcome ;-)
