### ISSUE TITLE
Fixed version (Cython==0.28.2) not usefull

### ISSUE THREAD

**Issue by guettli** [SAP/PyRFC#71]
The version of Cython is fixed to 0.28.2.

I use 0.28.4

I think fixing the version that strict is not useful. 

I am sure 0.28.4 is valid, too.

Here is the exception I get:

```
===> pip install -e git+https://github.com/SAP/PyRFC.git#egg=pyrfc
Obtaining pyrfc from git+https://github.com/SAP/PyRFC.git#egg=pyrfc
  Updating ./src/pyrfc clone
    Complete output from command python setup.py egg_info:
    Couldn't find index page for 'Sphinx' (maybe misspelled?)
    warning: no files found matching 'TODO'
    no previously-included directories found matching 'doc/_build'
    
    Installed /home/u/p/pyrfc-env/src/pyrfc/.eggs/Sphinx-1.3.1-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/u/p/pyrfc-env/src/pyrfc/setup.py", line 89, in <module>
        test_suite='pyrfc',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/u/p/pyrfc-env/local/lib/python2.7/site-packages/setuptools/dist.py", line 269, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/u/p/pyrfc-env/local/lib/python2.7/site-packages/setuptools/dist.py", line 313, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/u/p/pyrfc-env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 826, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/u/p/pyrfc-env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1085, in best_match
        dist = working_set.find(req)
      File "/home/u/p/pyrfc-env/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 695, in find
        raise VersionConflict(dist, req)
    pkg_resources.VersionConflict: (Cython 0.28.4 (/home/u/p/pyrfc-env/lib/python2.7/site-packages), Requirement.parse('Cython==0.28.2'))

```

**Comment by bsrdjan** [comment]
thanks, you are right, will remove the restriction. Per experience so far, new Cython version has never been a problem and no need to keep it fixed.
