### ISSUE TITLE
'X-Ratelimit-Limit'  error while using ORS too of QGIS

### ISSUE THREAD

**Issue by kkrani2009** [SAP/PyRFC#99]
An error has occurred while executing Python code: 

KeyError: 'X-Ratelimit-Limit' 
Traceback (most recent call last):
  File "C:/Users/k krishna rani samal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\gui\ORStoolsDialog.py", line 257, in run_gui_control
    response = clnt.request(provider['endpoints']['directions'], params)
  File "C:/Users/k krishna rani samal/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\ORStools\core\client.py", line 203, in request
    configmanager.write_env_var(env_var, response.headers[self.ENV_VARS[env_var]])
KeyError: 'X-Ratelimit-Limit'

**Comment by mpf82** [comment]
That's obviously not a PyRFC issue. Maybe you posted to the wrong github project?
